- name: Gather facts from the devices

  gather_facts: no

  hosts: routers

  tasks:

     - name: Gather facts from the ios device

       ios_facts:

          gather_subset: all

       register: ios_facts

       when: ansible_network_os == 'ios'

     - name: Save to a file

       copy:

          content: |
   
             Hostname: {{ ios_facts.ansible_facts.ansible_net_hostname }}

             Version: {{ ios_facts.ansible_facts.ansible_net_version }}

             Model: {{ ios_facts.ansible_facts.ansible_net_model }}

             Serial_number: {{ ios_facts.ansible_facts.ansible_net_serialnum }}

          dest: "{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d') }}.txt"

       when: ansible_network_os == 'ios'


     - name: Gather facts from the nxos devices

       nxos_facts:

         gather_subset: all

       register: nxos_facts

       when: ansible_network_os == 'nxos'

     - name: Save to a file

       copy:
 
          content: |

           Hostname: {{ nxos_facts.ansible_facts.ansible_net_hostname }}

           Version: {{ nxos_facts.ansible_facts.ansible_net_version }}
 
           Model: {{ nxos_facts.ansible_facts.ansible_net_model }}

           Serial_num: {{ nxos_facts.ansible_facts.ansible_net_serialnum }}

          dest: "{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d') }}.txt"
 
       when: ansible_network_os == 'nxos'






     
     

